configuration:
  project: de4ph
  year: 22
  year_start: 2021-12-20
  increment_length: 13
  iteration_length: 4
  ip_length: 1

agile_events:
  retrospective:
    - 2022-02-28
    - 2022-05-28
    - 2022-08-28
    - 2022-11-28
  vsrr:
    - 2022-03-01
    - 2022-06-01
    - 2022-09-01
    - 2022-12-01
  pirr:
    - 2022-03-12
    - 2022-06-12
    - 2022-09-12
    - 2022-12-12
  iteration planning:
    - 2022-01-13
    - 2022-02-10
  vision meeting:
    - 2022-03-14
  program epic review:
    - 2022-03-15
  planning sign off:
    - 2022-03-21

markers:
  RTE - upl. VSRR, PIRR, VSA:
    - increment_wk: 1
  RTE - nxt vision speakers:
    - increment_wk: 2
