configuration:
  project: de4ph
  year: 22
  year_start: 2021-12-20
  increment_length: 13
  iteration_length: 4
  ip_length: 1

agile_events:
  vision meeting:
    increment_wk: 1
  review meetings:
    increment_wk: 1
  VS retrospective:
    increment_wk: 1
  planning sign off:
    - increment_wk: 1
  iteration planning:
    - iteration_wk: 4

markers:
  RTE - upl. VSRR, PIRR, VSA:
    - 2022-02-15
    - 2022-01-30
    - increment_wk: 2
    - increment_wk: 2
    - increment_wk: 9
    - increment_wk: 6
    - increment_wk: 10
    - increment_wk: 11
    - increment_wk: 1
  RTE - nxt vision speakers:
    - increment_wk: 2
  RTE - upl. VSA, PIRR, VSRR:
  RTE - req. VSA, PIRR, VSRR:
  SM - plan next increment:
  SM - complete PIRR:
  SM - update team + certs:
  SM - check kpi dashboard:
  RTE - business objectives:
  SM - plan next retro:
  RTE - nxt IP week @IPM:
