configuration:
  project: de4ph
  year: 22
  year_start: 2021-12-20
  increment_length: 13
  iteration_length: 4
  ip_length: 1

agile_events:
  vision meeting:
    increment_wk: 1
  review meetings:
    increment_wk: 1
  VS retrospective:
    increment_wk: 1
  planning sign off:
    - increment_wk: 1
  iteration planning:
    - iteration_wk: 4

markers:
  PO update SIA:
    - 2022-02-15
  PO update stakeholders:
    - 2022-01-30
  PO update VSA:
    - increment_wk: 2
  RTE vision speakers:
    - increment_wk: 2
  RTE vision agenda:
    - increment_wk: 9
  RTE upload VSA, PIRR, VSRR:
    - increment_wk: 6
  RTE PI review template:
    - increment_wk: 10
  RTE agenda IP week:
    - increment_wk: 11
  SM plan sprint reviews:
    - increment_wk: 1
  SM plan next IP week:
    - increment_wk: 2
